### ISSUE TITLE
How to use the code in main.c

### ISSUE THREAD

**Issue by ozdemirmcihad** [PCov3r/HX711-STM32-Library#1]
Can you tell me how to use the code in main.c file? I did not understand how to use it.

2-) Can I control and measure both channels at the same time?

**Comment by PCov3r** [comment]
Hi,

I wrote this library long ago but forgot to add anything to the example file in main.c.
I will try to find some time and write a short example on how to set up the sensor.

Regarding your 2nd question, I do not know if the sensor allows it, but in any case I haven't implemented it.
Regards
